const data = {
	products: [
		{
			name: 'Free Shirt',
			slug: 'free-shirt',
			category: 'Shirts',
			image: '/images/shirt1.jpg',
			price: 70,
			quantity: 1,
			countInStock: 10,
		},
		{
			name: 'Fit Shirt',
			slug: 'fit-shirt',
			category: 'Shirts',
			image: '/images/shirt2.jpg',
			price: 80,
			quantity: 1,
			countInStock: 5,
		},
		{
			name: 'Slim Shirt',
			slug: 'slim-shirt',
			category: 'Shirts',
			image: '/images/shirt3.jpg',
			price: 90,
			quantity: 1,
			countInStock: 0,
		},
		{
			name: 'Golf Pants',
			slug: 'golf-pants',
			category: 'Pants',
			image: '/images/pants1.jpg',
			price: 90,
			quantity: 1,
			countInStock: 12,
		},
		{
			name: 'Fit Pants',
			slug: 'fit-pants',
			category: 'Pants',
			image: '/images/pants2.jpg',
			price: 95,
			quantity: 1,
			countInStock: 3,
		},
		{
			name: 'Classic Pants',
			slug: 'classic-pants',
			category: 'Pants',
			image: '/images/pants3.jpg',
			price: 75,
			brand: 'Casely',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular pants',
			quantity: 1,
		},
	],
};

export default data;
